mutation InsertProductOxelaWithImage(
  $handle: String!
  $title: String!
  $description: String
  $availableForSale: Boolean!
  $productType: String
  $imageUrl: String!
  $imageAltText: String
  $imageWidth: Int!
  $imageHeight: Int!
  $featured: Boolean!
  $displayPosition: Int!
) @auth(level: PUBLIC) @transaction {
  # Étape 0 : s'assurer que le handle n'existe pas déjà
  query
    @check(
      expr: "response.query.products.size() == 0"
      message: "A product with this handle already exists"
    )
    @redact {
    products(where: { handle: { eq: $handle } }) {
      id
    }
  }

  # Étape 1 : création du produit
  product: product_insert(
    data: {
      handle: $handle
      title: $title
      description: $description
      productType: $productType
      availableForSale: $availableForSale
    }
  ) @check(expr: "this != null", message: "Product creation failed")

  # Étape 2 : création de l'image
  productImage_insert(
    data: {
      productId_expr: "response.product.id"
      url: $imageUrl
      altText: $imageAltText
      width: $imageWidth
      height: $imageHeight
      featured: $featured
      displayPosition: $displayPosition
    }
  ) @check(expr: "this != null", message: "Image creation failed")

  # # Étape 3 : mise à jour du produit avec l'image en vedette
  product_update(
    key: { id_expr: "response.product.id" }
    data: { featuredImageId_expr: "response.productImage_insert.id" }
  ) @check(expr: "this != null", message: "Failed to link featured image")
}
