query getfeaturedImagesOxela @auth(level: PUBLIC) {
  productImages {
    id
    url
    width
    height
    altText
  }
}

# Get all products
query getProductsOxela @auth(level: PUBLIC) {
  products(limit: 100) {
    id
    title
    description
    handle
    availableForSale
    createdAt
    updatedAt
    featuredImage {
      url
      width
      height
      altText
    }
    seo {
      title
      description
      keywords
    }
  }
}

query getProductByIdOxela($id: UUID!) @auth(level: PUBLIC) {
  product(id: $id) {
    id
    featuredImage {
      url
      width
      height
      altText
    }
    seo {
      title
      description
      keywords
    }

    handle
    title
    description
    productType
    availableForSale

    createdAt
    updatedAt
  }
}

query sEOSOxela @auth(level: PUBLIC) {
  sEOS {
    id
    title
    description
    keywords
  }
}

query getSEOByIdOxela($id: UUID!) @auth(level: PUBLIC) {
  sEO(id: $id) {
    id
    title
    description
    keywords
  }
}
