type SEO @table {
  id: UUID! @default(expr: "uuidV4()")
  title: String!
  description: String!
  keywords: String!
}

type ProductImage @table {
  id: UUID! @default(expr: "uuidV4()")
  product: Product! @unique

  url: String! @col(name: "url", dataType: "text")
  altText: String @col(name: "alt_text", dataType: "text")
  width: Int! @col(name: "width", dataType: "int")
  height: Int! @col(name: "height", dataType: "int")

  featured: Boolean! @col(name: "featured", dataType: "boolean")
  displayPosition: Int! @col(name: "display_position", dataType: "int")
}

# Product
type Product @table {
  id: UUID! @default(expr: "uuidV4()")
  featuredImage: ProductImage
  seo: SEO

  handle: String! @col(name: "handle", dataType: "varchar(100)") @unique
  title: String! @col(name: "title", dataType: "varchar(100)")
  description: String @col(name: "description", dataType: "text")
  # price ? NOPE
  productType: String @col(name: "product_type", dataType: "varchar(100)")
  availableForSale: Boolean!
    @col(name: "available_for_sale", dataType: "boolean")

  createdAt: Date! @default(expr: "request.time")
  updatedAt: Date! @default(expr: "request.time")
}
